### ISSUE TITLE
X2C issue

### ISSUE THREAD

**Issue by FredvanderWindt** [z390development/z390#438] opened 2022-08-17 10:14 UTC
X2C function only works correctly for one byte hexadecimal string length input. X2C and X2B functions fail on multi-byte input data.

Example:

`&SRC     SETC  X2C('30313233343536373839616263646566414243444546')`

Returns an error, during macro expansion process:

```
14:44:20 FQM8921C  MZ390 START USING z390 V1.7.07 ON J2SE 1.8.0_333 05/12/22
MZ390E abort 84 file=1 line=43 internal system exception - java.lang.NumberFormatException: For input string: "30313233343536373839616263646566414243444546"
AZ390E error 165       (1/43)42   * MZ390E abort 84 file=1 line=43 internal system exception - java.lang.NumberFormatException: For input string: "30313233343536373839616263646566414243444546"
14:44:24 FQM8921C  MZ390 ENDED   RC=16 SEC= 3 MEM(MB)= 74 IO=181
```

**Proposed fix**
This can be fixed in function exec_pc_x2c in mz390.java.

**Original**

```
 private void exec_pc_x2c(){
    	/*
    	 * convert hex string to char string
    	 */
    	check_setc_quotes(1); // RPI 1139
    	setc_value1 = get_setc_stack_value();
    	seta_value = Integer.valueOf(setc_value1,16);
		setc_value = ""
	       + (char)tz390.ebcdic_to_ascii[seta_value >>> 24]
	       + (char)tz390.ebcdic_to_ascii[seta_value >>> 16 & 0xff]         
	       + (char)tz390.ebcdic_to_ascii[seta_value >>> 8  & 0xff]
	       + (char)tz390.ebcdic_to_ascii[seta_value        & 0xff]		       ;
	put_setc_stack_var();
    }
```

**Fixed**

```
    private void exec_pc_x2c(){
    	/*
    	 * convert hex string to char string
    	 */
    	check_setc_quotes(1); // RPI 1139
    	setc_value1 = get_setc_stack_value();
//ING    	seta_value = Integer.valueOf(setc_value1,16);
//ING	setc_value = ""
//ING	       + (char)tz390.ebcdic_to_ascii[seta_value >>> 24]
//ING	       + (char)tz390.ebcdic_to_ascii[seta_value >>> 16 & 0xff]         
//ING	       + (char)tz390.ebcdic_to_ascii[seta_value >>> 8  & 0xff]
//ING	       + (char)tz390.ebcdic_to_ascii[seta_value        & 0xff]	 
//ING	       ;
        StringBuilder stb = new StringBuilder("");
        for (int i = 0; i < setc_value1.length(); i += 2) {
            String str = setc_value1.substring(i, i + 2);
            stb.append((char) Integer.parseInt(str, 16));
        }
        setc_value = stb.toString(); 	
        put_setc_stack_var();
    }

```

**Comment by FredvanderWindt** [comment] 2022-08-17 11:52
I just noticed that this bug is also registered under RPI 1646.

**Comment by dsh33782** [comment] 2022-08-17 13:03
Fred, thanks.  When this gets fixed, we can close both issues.

**Comment by adelosa** [comment] 2022-10-01 07:40
Closing as duplicate of #216

**Closed as completed by adelosa** 2022-10-01 07:40 UTC
