### ISSUE TITLE
Build failing when no repo tags

### ISSUE THREAD

**Issue by chookperson** [z390development/z390#472] opened 2023-02-17 01:27 UTC
As explained, the break was due to a lack of wifi at my aged-care facility.
A friend managed to set me up with wifi via my phone.

cd c:\z390dev\z390

entered ..... build.bat
got
c:\z390dev\z390>build.bat
Could Not Find c:\z390dev\z390\jar\z390.jar
src\az390.java
src\ez390.java
src\gz390.java
src\gz390_screen.java
src\iz390.java
src\lz390.java
src\MessageBox.java
src\mz390.java
src\pz390.java
src\sz390.java
src\test_screen.java
src\test_unicode.java
src\tz390.java
src\vz390.java
src\z390.java
src\zACB.java
src\zc390.java
src\zCatVAIX.java
src\zCatVCLR.java
       19 file(s) copied.
        1 file(s) copied.
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
gz390.java:574: warning: [removal] SecurityManager in java.lang has been deprecated and marked for removal
            SecurityManager sm = System.getSecurityManager();
            ^
gz390.java:574: warning: [removal] getSecurityManager() in System has been deprecated and marked for removal
            SecurityManager sm = System.getSecurityManager();
                                       ^
z390.java:423: warning: [removal] SecurityManager in java.lang has been deprecated and marked for removal
            SecurityManager sm = System.getSecurityManager();
            ^
z390.java:423: warning: [removal] getSecurityManager() in System has been deprecated and marked for removal
            SecurityManager sm = System.getSecurityManager();
                                       ^
4 warnings
fatal: No names found, cannot describe anything.
Version is uncontrolled - add FORCE parm to ignore
bat\bldjar ERROR: Error finding z390 version number
build.bat ERROR: Encountered RC 8 - exiting

c:\z390dev\z390>

John Hennesy

**Comment by adelosa** [comment] 2023-02-17 06:37
That error is because the source is not in a git controlled environment. 
Did you copy the source after the git clone? 
If so, that's the reason. You can force the build by adding force to the command.

**Comment by chookperson** [comment] 2023-02-17 17:47
I used the FORCE parameter and got

c:\z390dev\z390>build.bat force
Could Not Find c:\z390dev\z390\jar\z390.jar
src\az390.java
src\ez390.java
src\gz390.java
src\gz390_screen.java
src\iz390.java
src\lz390.java
src\MessageBox.java
src\mz390.java
src\pz390.java
src\sz390.java
src\test_screen.java
src\test_unicode.java
src\tz390.java
src\vz390.java
src\z390.java
src\zACB.java
src\zc390.java
src\zCatVAIX.java
src\zCatVCLR.java
       19 file(s) copied.
        1 file(s) copied.
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
gz390.java:574: warning: [removal] SecurityManager in java.lang has been deprecated and marked for removal
            SecurityManager sm = System.getSecurityManager();
            ^
gz390.java:574: warning: [removal] getSecurityManager() in System has been deprecated and marked for removal
            SecurityManager sm = System.getSecurityManager();
                                       ^
z390.java:423: warning: [removal] SecurityManager in java.lang has been deprecated and marked for removal
            SecurityManager sm = System.getSecurityManager();
            ^
z390.java:423: warning: [removal] getSecurityManager() in System has been deprecated and marked for removal
            SecurityManager sm = System.getSecurityManager();
                                       ^
4 warnings
fatal: No names found, cannot describe anything.
Version is uncontrolled - add FORCE parm to ignore
bat\bldjar ERROR: Error finding z390 version number
build.bat ERROR: Encountered RC 8 - exiting

**Comment by adelosa** [comment] 2023-02-17 20:19
Hi John. That looks right to me. You should have got past that error. @abekornelis has done some work on the windows batch files since I originally worked on the build. I suspect we may have a regression here.
@abekornelis - can you have a look at this? I don't run Windows anymore.

**Comment by abekornelis** [comment] 2023-02-18 10:39
I have comparable results using John's fork:

D:\z390dev>git clone https://github.com/chookperson/z390.git z390tmp
Cloning into 'z390tmp'...
remote: Enumerating objects: 10052, done.
remote: Total 10052 (delta 0), reused 0 (delta 0), pack-reused 10052 eceiving objects: 100% (10052/10052), 8.07 MiB | 1
Receiving objects: 100% (10052/10052), 8.23 MiB | 1.53 MiB/s, done.
Resolving deltas: 100% (7149/7149), done.
Updating files: 100% (2625/2625), done.

D:\z390dev>cd z390tmp

D:\z390dev\z390tmp>build.bat
Could Not Find D:\z390dev\z390tmp\jar\*.java
Could Not Find D:\z390dev\z390tmp\jar\*.class
Could Not Find D:\z390dev\z390tmp\jar\z390.jar
src\az390.java
src\ez390.java
src\gz390.java
src\gz390_screen.java
src\iz390.java
src\lz390.java
src\MessageBox.java
src\mz390.java
src\pz390.java
src\sz390.java
src\test_screen.java
src\test_unicode.java
src\tz390.java
src\vz390.java
src\z390.java
src\zACB.java
src\zc390.java
src\zCatVAIX.java
src\zCatVCLR.java
       19 file(s) copied.
        1 file(s) copied.
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
fatal: No names found, cannot describe anything.
Version is uncontrolled - add FORCE parm to ignore
bat\bldjar ERROR: Error finding z390 version number
build.bat ERROR: Encountered RC 8 - exiting

**Comment by abekornelis** [comment] 2023-02-18 10:55
Problem does NOT reproduce on z390development main branch, nor on  my own fork. Problem must be local to John's fork. Will continue investigation.

**Comment by abekornelis** [comment] 2023-02-18 11:37
The problem occurs ONLY on John's fork. Both on his local system and on a clone on my local system. 
So the problem is local to John's clone, not to his local environment.
Strange enough - the clone I made has no recent changes. The only difference between john's fork and the main repo is a backlog of two commits. I suggest John should first update his fork, then his clone, then retry.

@John please do the following:
1) go to github.com to your own fork
2) on the pull-down for branches, select the main branch
3) just below the green "Code" button, you will find a "sync fork" button, use that to update your fork.

4) on your local machine open a cmd box and go to the directory that holds your clone of the repository
5) issue git status - to validate you're okay
6) issue git switch main - to switch to the main branch
7) issue git status - to validate you're on the main branch now
8) issue git pull - to update your main branch
9) issue build.bat - to see if you can now create the z390 executables.

**Comment by chookperson** [comment] 2023-02-21 01:51
Abe,
I followed your instructions

1.  GO TO GITHUB.COM TO YOUR OWN FORK.
2.  ON THE PULL-DOWN FOR BRANCHES,
    SELECT THE MAIN BRANCH.
    I entere "github.com/chookperson/z390".
3.  JUST BELOW THE GREEN "CODE" BUTTON, YOU WILL FIND A
    "SYNC FORK" BUTTON, USE THAT TO UPDATE YOUR FORK.
    It says "this branch is out of date" but has a green
    Update button below. Pressed that.
    It replied
    "Successfully fetched and fast-forwarded from upstream 
     z390development:main."

4.  ON YOUR LOCAL MACHINE GO TO THE DIRECTORY THAT HOLDS YOUR
    CLONE OF THE REPOSITORY.
    cd c:\z390dev\z390

5.  ISSUE GIT STATUS - TO VALIDATE YOU'RE OK.
    It replies
    "fatal: cannot handle STATUS as a builtin"
    must be in lower-case
    "On branch DB2
     nothing to commit, working tree clean"

6.  ISSUE GIT SWITCH MAIN - TO VALIDATE YOU'RE OK.
    git switch main
    It replies
    "Switched to branch 'main'
     Your branch is up to date with 'origin/main'."

7.  ISSUE GIT STATUS - TO VALIDATE YOU'RE ON THE MAIN BRANCH NOW
    git status
    It replies
    "On branch main
     Your branch is up to date with 'origin/main'.
     nothing to commit, working tree clean"

8.  ISSUE GIT PULL - TO UPDATE YOUR MAIN BRANCH
    git pull
    It replies
    "remote: Enumerating objects: 70, done.
     remote: Counting objects: 100% (54/54), done.
     remote: Compressing objects: 100% (40/40), done.
     remote: Total 70 (delta 7), reused 31 (delta 4), pack-reused 16
     Unpacking objects: 100% (70/70), 110.26 KiB | 149.00 KiB/s, done.
     From https://github.com/chookperson/z390
        0f9cdbd..b68df64  main       -> origin/main
     Updating 0f9cdbd..b68df64
     Fast-forward
      .github/workflows/build.yml                        |   2 +-
      .github/workflows/docs.yml                         |   2 +-
      BUILD.BAT                                          |  18 +-
      build.sh                                           |  18 +-
      doc/contributing/contribute_code.md                |   2 +-
      doc/contributing/contributing_zcobol.md            |  51 ++
      doc/getting_started/quickstart.md                  |   5 +-
      doc/getting_started/zCOBOL_Overview.md             | 159 +++++
      doc/reference/.pages                               |   1 -
      doc/reference/assist.md                            |   4 +-
      doc/reference/structured_program.md                |   2 +-
      .../zCOBOL_NIST_COBOL_1985_Test_Results.md         | 717 +++++++++++++++++++++
      doc/reference/zCOBOL_System_Programmer_Guide.md    | 268 ++++++++
      doc/user_guide/.pages                              |   4 +
      doc/user_guide/{ => z390}/commands.md              |   6 +-
      doc/user_guide/{ => z390}/structured_macro.md      |   0
      doc/user_guide/{options => z390}/z390_filetypes.md |   0
      doc/user_guide/{options => z390}/z390_options.md   |   0
      doc/{reference => user_guide}/zCICS/index.md       |   0
      .../zCICS/zcics_app_prog_guide.md                  |   0
      doc/user_guide/zCOBOL/.pages                       |   5 +
      doc/user_guide/zCOBOL/commands.md                  |  37 ++
      .../zCOBOL/zCOBOL_System_Programmer_Guide.md       | 282 ++++++++
      doc/user_guide/zCOBOL/zCOBOL_User_Guide.md         | 164 +++++
      .../{options => zCOBOL}/zCOBOL_filetypes.md        |   0
      .../{options => zCOBOL}/zCOBOL_options.md          |   0
      doc/user_guide/zCOBOL_User_Guide.md                | 202 ++++++
      z390test/.gitignore                                |  48 ++
      z390test/LICENSE                                   | 339 ++++++++++
      z390test/README.md                                 | 242 +++++++
      z390test/build.gradle                              |  22 +
      z390test/gradle/wrapper/gradle-wrapper.jar         | Bin 0 -> 59821 bytes
      z390test/gradle/wrapper/gradle-wrapper.properties  |   5 +
      z390test/gradlew                                   | 234 +++++++
      z390test/gradlew.bat                               |  89 +++
      z390test/settings.gradle                           |   2 +
      .../src/main/groovy/org/z390/test/z390Test.groovy  | 274 ++++++++
      .../test/groovy/org/z390/test/RunAsmDemos.groovy   |  40 ++
      .../test/groovy/org/z390/test/RunAsmTests.groovy   | 101 +++
      .../src/test/groovy/org/z390/test/RunAssist.groovy |  48 ++
      .../test/groovy/org/z390/test/RunCblDemos.groovy   |  63 ++
      .../test/groovy/org/z390/test/RunCblTests.groovy   |  29 +
      .../test/groovy/org/z390/test/RunCmdProc.groovy    |  89 +++
      .../src/test/groovy/org/z390/test/RunRTBSAM.groovy |  38 ++
      .../src/test/groovy/org/z390/test/RunRTQSAM.groovy |  34 +
      .../test/groovy/org/z390/test/RunRtTests.groovy    | 104 +++
      .../test/groovy/org/z390/test/RunSortTests.groovy  |  76 +++
      .../test/groovy/org/z390/test/RunTestOption.groovy | 109 ++++
      .../groovy/org/z390/test/RunZSTRMacTest.groovy     | 165 +++++
      .../test/groovy/org/z390/test/RunZparTests.groovy  |  26 +
      .../test/groovy/org/z390/test/TestZ390Test.groovy  |  62 ++
      51 files changed, 4149 insertions(+), 39 deletions(-)
      create mode 100644 doc/contributing/contributing_zcobol.md
      create mode 100644 doc/getting_started/zCOBOL_Overview.md
      create mode 100644 doc/reference/zCOBOL_NIST_COBOL_1985_Test_Results.md
      create mode 100644 doc/reference/zCOBOL_System_Programmer_Guide.md
      create mode 100644 doc/user_guide/.pages
      rename doc/user_guide/{ => z390}/commands.md (95%)
      rename doc/user_guide/{ => z390}/structured_macro.md (100%)
      rename doc/user_guide/{options => z390}/z390_filetypes.md (100%)
      rename doc/user_guide/{options => z390}/z390_options.md (100%)
      rename doc/{reference => user_guide}/zCICS/index.md (100%)
      rename doc/{reference => user_guide}/zCICS/zcics_app_prog_guide.md (100%)
      create mode 100644 doc/user_guide/zCOBOL/.pages
      create mode 100644 doc/user_guide/zCOBOL/commands.md
      create mode 100644 doc/user_guide/zCOBOL/zCOBOL_System_Programmer_Guide.md
      create mode 100644 doc/user_guide/zCOBOL/zCOBOL_User_Guide.md
      rename doc/user_guide/{options => zCOBOL}/zCOBOL_filetypes.md (100%)
      rename doc/user_guide/{options => zCOBOL}/zCOBOL_options.md (100%)
      create mode 100644 doc/user_guide/zCOBOL_User_Guide.md
      create mode 100644 z390test/.gitignore
      create mode 100644 z390test/LICENSE
      create mode 100644 z390test/README.md
      create mode 100644 z390test/build.gradle
      create mode 100644 z390test/gradle/wrapper/gradle-wrapper.jar
      create mode 100644 z390test/gradle/wrapper/gradle-wrapper.properties
      create mode 100755 z390test/gradlew
      create mode 100644 z390test/gradlew.bat
      create mode 100644 z390test/settings.gradle
      create mode 100644 z390test/src/main/groovy/org/z390/test/z390Test.groovy
      create mode 100644 z390test/src/test/groovy/org/z390/test/RunAsmDemos.groovy
      create mode 100644 z390test/src/test/groovy/org/z390/test/RunAsmTests.groovy
      create mode 100644 z390test/src/test/groovy/org/z390/test/RunAssist.groovy
      create mode 100644 z390test/src/test/groovy/org/z390/test/RunCblDemos.groovy
      create mode 100644 z390test/src/test/groovy/org/z390/test/RunCblTests.groovy
      create mode 100644 z390test/src/test/groovy/org/z390/test/RunCmdProc.groovy
      create mode 100644 z390test/src/test/groovy/org/z390/test/RunRTBSAM.groovy
      create mode 100644 z390test/src/test/groovy/org/z390/test/RunRTQSAM.groovy
      create mode 100644 z390test/src/test/groovy/org/z390/test/RunRtTests.groovy
      create mode 100644 z390test/src/test/groovy/org/z390/test/RunSortTests.groovy
      create mode 100644 z390test/src/test/groovy/org/z390/test/RunTestOption.groovy
      create mode 100644 z390test/src/test/groovy/org/z390/test/RunZSTRMacTest.groovy
      create mode 100644 z390test/src/test/groovy/org/z390/test/RunZparTests.groovy
      create mode 100644 z390test/src/test/groovy/org/z390/test/TestZ390Test.groovy"

9.  ISSUE BUILD.BAT - TO SEE IF YOU CAN NOW CREATE THE Z390
    EXECUTABLES.
    build.bat
    It replies
    "Could Not Find C:\z390dev\z390\jar\z390.jar
     src\az390.java
     src\ez390.java
     src\gz390.java
     src\gz390_screen.java
     src\iz390.java
     src\lz390.java
     src\MessageBox.java
     src\mz390.java
     src\pz390.java
     src\sz390.java
     src\test_screen.java
     src\test_unicode.java
     src\tz390.java
     src\vz390.java
     src\z390.java
     src\zACB.java
     src\zc390.java
     src\zCatVAIX.java
     src\zCatVCLR.java
             19 file(s) copied.
             1 file(s) copied.
     java version "17.0.1" 2021-10-19 LTS
     Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
     Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
     gz390.java:574: warning: [removal] SecurityManager in java.lang has been deprecated and marked for removal
            SecurityManager sm = System.getSecurityManager();
            ^
     gz390.java:574: warning: [removal] getSecurityManager() in System has been deprecated and marked for removal
            SecurityManager sm = System.getSecurityManager();
                                       ^
     z390.java:423: warning: [removal] SecurityManager in java.lang has been deprecated and marked for removal
            SecurityManager sm = System.getSecurityManager();
            ^
     z390.java:423: warning: [removal] getSecurityManager() in System has been deprecated and marked for removal
            SecurityManager sm = System.getSecurityManager();
                                       ^
     4 warnings
     fatal: No names found, cannot describe anything.
     Version is uncontrolled - add FORCE parm to ignore
     bat\bldjar ERROR: Error finding z390 version number
     build.bat ERROR: Encountered RC 8 - exiting"
   
Should I rerun with force?

**Comment by abekornelis** [comment] 2023-02-21 08:05
No, please give me/us some time to further investigate. 
The offending code exists in all branches - so it surprises me that the problem occurs on your fork both on your machine and on mine, but not in any other forks. 
@adelosa could it be some compiler setting that has been changed in John's fork, but not in ours ??
Could you please have a look at it?

**Comment by adelosa** [comment] 2023-02-21 08:08
I'll have a look and see if I can work it out.

**Comment by adelosa** [comment] 2023-02-21 08:53
I have not seen this before, but I have had issues in the past having to explicitly fetch tags from GitHub so it does not surprise me.. Will have a think about how to avoid this for future contributors (some repo setting, more documentation etc)

The reason for the error is because the fork process has not pulled any of the tags. 
Tags are used to determine the name, so without them you get the 

`fatal: No names found, cannot describe anything.`

It seems that the default git clone action only goes back so far with regards to tags.
To fix, you need to pull the tags from the main repository which is nominated as `upstream`. 

Follow the following steps in your clone directory:

```
git remote add upstream https://github.com/z390development/z390.git
git checkout main
git remote prune origin
git fetch -p upstream 
git rebase upstream/main
git push origin --follow-tags
```

Once complete, then try the build again.

What this is doing:
* Adds the main z390 repo as a remote to your clone (called upstream).
* Then it fetches the commits and tags from the z390 repo (upstream).
* Applies (rebase) updates and tags to your local (main)
* Pushes the update and tags  back to your fork on GitHub (origin)

I tested this on my local machine and it worked.

**Comment by abekornelis** [comment] 2023-02-21 18:39
Anthony - thanks for figuring that out. It's a pretty complex recipe, but I guess John should be able to follow your step-by-step approach. Would be nice if we could fix the fork process - that's really a setback if it selectively omits tags :-( 
@John - would you please give it a try with the above instructions as provided by Anthony?

**Comment by chookperson** [comment] 2023-02-22 22:53
everything looked ok


c:\z390dev\z390>git remote add upstream https://github.com/z390development/z390.git

c:\z390dev\z390>git checkout main
Already on 'main'
Your branch is up to date with 'origin/main'.

c:\z390dev\z390>git remote prune origin

c:\z390dev\z390>git fetch -p upstream
remote: Enumerating objects: 864, done.
remote: Counting objects: 100% (141/141), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 864 (delta 61), reused 108 (delta 36), pack-reused 723Receiving objects: 100% (864/864), 1.46 MiB | 980.00Receiving objects: 100% (864/864), 1.92 MiB | 1.02 MiB/s, done.

Resolving deltas: 100% (303/303), done.
From https://github.com/z390development/z390
 * [new branch]      gh-pages      -> upstream/gh-pages
 * [new branch]      main          -> upstream/main
 * [new tag]         v0.0.00       -> v0.0.00
 * [new tag]         v1.0.00       -> v1.0.00
 * [new tag]         v1.0.12       -> v1.0.12
 * [new tag]         v1.0.13       -> v1.0.13
 * [new tag]         v1.0.13a      -> v1.0.13a
 * [new tag]         v1.0.13b      -> v1.0.13b
 * [new tag]         v1.0.13c      -> v1.0.13c
 * [new tag]         v1.0.13d      -> v1.0.13d
 * [new tag]         v1.0.13e      -> v1.0.13e
 * [new tag]         v1.1.00       -> v1.1.00
 * [new tag]         v1.1.00c      -> v1.1.00c
 * [new tag]         v1.1.00d      -> v1.1.00d
 * [new tag]         v1.1.00e      -> v1.1.00e
 * [new tag]         v1.1.00f      -> v1.1.00f
 * [new tag]         v1.1.01       -> v1.1.01
 * [new tag]         v1.1.01a      -> v1.1.01a
 * [new tag]         v1.1.01b      -> v1.1.01b
 * [new tag]         v1.1.01c      -> v1.1.01c
 * [new tag]         v1.1.01e      -> v1.1.01e
 * [new tag]         v1.1.01f      -> v1.1.01f
 * [new tag]         v1.1.02       -> v1.1.02
 * [new tag]         v1.1.02a      -> v1.1.02a
 * [new tag]         v1.1.02b      -> v1.1.02b
 * [new tag]         v1.1.02c      -> v1.1.02c
 * [new tag]         v1.2.00       -> v1.2.00
 * [new tag]         v1.2.00a      -> v1.2.00a
 * [new tag]         v1.2.00b      -> v1.2.00b
 * [new tag]         v1.2.00c      -> v1.2.00c
 * [new tag]         v1.2.00d      -> v1.2.00d
 * [new tag]         v1.2.00e      -> v1.2.00e
 * [new tag]         v1.2.00f      -> v1.2.00f
 * [new tag]         v1.2.00g      -> v1.2.00g
 * [new tag]         v1.3.00       -> v1.3.00
 * [new tag]         v1.3.00a      -> v1.3.00a
 * [new tag]         v1.3.01       -> v1.3.01
 * [new tag]         v1.3.02       -> v1.3.02
 * [new tag]         v1.3.02b      -> v1.3.02b
 * [new tag]         v1.3.02g      -> v1.3.02g
 * [new tag]         v1.3.02h      -> v1.3.02h
 * [new tag]         v1.3.03       -> v1.3.03
 * [new tag]         v1.3.03a      -> v1.3.03a
 * [new tag]         v1.3.03b      -> v1.3.03b
 * [new tag]         v1.3.03c      -> v1.3.03c
 * [new tag]         v1.3.04       -> v1.3.04
 * [new tag]         v1.3.04a      -> v1.3.04a
 * [new tag]         v1.3.04b      -> v1.3.04b
 * [new tag]         v1.3.05       -> v1.3.05
 * [new tag]         v1.3.06       -> v1.3.06
 * [new tag]         v1.3.06a      -> v1.3.06a
 * [new tag]         v1.3.07       -> v1.3.07
 * [new tag]         v1.3.07a      -> v1.3.07a
 * [new tag]         v1.3.07b      -> v1.3.07b
 * [new tag]         v1.3.07c      -> v1.3.07c
 * [new tag]         v1.3.07d      -> v1.3.07d
 * [new tag]         v1.3.07e      -> v1.3.07e
 * [new tag]         v1.3.07f      -> v1.3.07f
 * [new tag]         v1.3.08       -> v1.3.08
 * [new tag]         v1.3.08a      -> v1.3.08a
 * [new tag]         v1.3.08b      -> v1.3.08b
 * [new tag]         v1.3.08c      -> v1.3.08c
 * [new tag]         v1.3.08d      -> v1.3.08d
 * [new tag]         v1.3.08e      -> v1.3.08e
 * [new tag]         v1.3.08f      -> v1.3.08f
 * [new tag]         v1.3.08g      -> v1.3.08g
 * [new tag]         v1.3.08h      -> v1.3.08h
 * [new tag]         v1.3.09       -> v1.3.09
 * [new tag]         v1.4.00       -> v1.4.00
 * [new tag]         v1.4.00c      -> v1.4.00c
 * [new tag]         v1.4.00d      -> v1.4.00d
 * [new tag]         v1.4.00e      -> v1.4.00e
 * [new tag]         v1.4.00f      -> v1.4.00f
 * [new tag]         v1.4.01       -> v1.4.01
 * [new tag]         v1.4.01a      -> v1.4.01a
 * [new tag]         v1.4.01b      -> v1.4.01b
 * [new tag]         v1.4.01c      -> v1.4.01c
 * [new tag]         v1.4.01d      -> v1.4.01d
 * [new tag]         v1.4.01e      -> v1.4.01e
 * [new tag]         v1.4.01f      -> v1.4.01f
 * [new tag]         v1.4.02       -> v1.4.02
 * [new tag]         v1.4.02a      -> v1.4.02a
 * [new tag]         v1.4.02b      -> v1.4.02b
 * [new tag]         v1.4.02c      -> v1.4.02c
 * [new tag]         v1.4.02d      -> v1.4.02d
 * [new tag]         v1.4.02e      -> v1.4.02e
 * [new tag]         v1.4.03       -> v1.4.03
 * [new tag]         v1.4.03a      -> v1.4.03a
 * [new tag]         v1.4.03b      -> v1.4.03b
 * [new tag]         v1.4.03c      -> v1.4.03c
 * [new tag]         v1.4.03d      -> v1.4.03d
 * [new tag]         v1.4.04       -> v1.4.04
 * [new tag]         v1.4.04a      -> v1.4.04a
 * [new tag]         v1.5.00       -> v1.5.00
 * [new tag]         v1.5.00a      -> v1.5.00a
 * [new tag]         v1.5.00b      -> v1.5.00b
 * [new tag]         v1.5.00b2     -> v1.5.00b2
 * [new tag]         v1.5.00c      -> v1.5.00c
 * [new tag]         v1.5.00d      -> v1.5.00d
 * [new tag]         v1.5.00e      -> v1.5.00e
 * [new tag]         v1.5.01       -> v1.5.01
 * [new tag]         v1.5.01a      -> v1.5.01a
 * [new tag]         v1.5.01b      -> v1.5.01b
 * [new tag]         v1.5.01c      -> v1.5.01c
 * [new tag]         v1.5.01d      -> v1.5.01d
 * [new tag]         v1.5.02       -> v1.5.02
 * [new tag]         v1.5.03       -> v1.5.03
 * [new tag]         v1.5.04       -> v1.5.04
 * [new tag]         v1.5.05       -> v1.5.05
 * [new tag]         v1.5.06       -> v1.5.06
 * [new tag]         v1.5.06rc1    -> v1.5.06rc1
 * [new tag]         v1.5.06rc2    -> v1.5.06rc2
 * [new tag]         v1.5.06rc3    -> v1.5.06rc3
 * [new tag]         v1.5.06rc4    -> v1.5.06rc4
 * [new tag]         v1.6.00b01    -> v1.6.00b01
 * [new tag]         v1.6.00b02    -> v1.6.00b02
 * [new tag]         v1.6.00b03    -> v1.6.00b03
 * [new tag]         v1.6.00b04    -> v1.6.00b04
 * [new tag]         v1.6.00b05    -> v1.6.00b05
 * [new tag]         v1.6.00b06    -> v1.6.00b06
 * [new tag]         v1.6.00b07    -> v1.6.00b07
 * [new tag]         v1.6.00b08    -> v1.6.00b08
 * [new tag]         v1.6.00b09    -> v1.6.00b09
 * [new tag]         v1.6.00b10    -> v1.6.00b10
 * [new tag]         v1.6.00b11    -> v1.6.00b11
 * [new tag]         v1.6.00b12    -> v1.6.00b12
 * [new tag]         v1.7.00       -> v1.7.00
 * [new tag]         v1.7.01       -> v1.7.01
 * [new tag]         v1.7.02       -> v1.7.02
 * [new tag]         v1.7.03       -> v1.7.03
 * [new tag]         v1.7.04       -> v1.7.04
 * [new tag]         v1.7.05       -> v1.7.05
 * [new tag]         v1.7.05a      -> v1.7.05a
 * [new tag]         v1.7.06       -> v1.7.06
 * [new tag]         v1.7.07       -> v1.7.07
 * [new tag]         v1.8.0        -> v1.8.0
 * [new tag]         v1.8.0-beta.1 -> v1.8.0-beta.1
 * [new tag]         v1.8.0-rc.1   -> v1.8.0-rc.1
 * [new tag]         v1.8.1        -> v1.8.1
 * [new tag]         v1.8.1-rc.1   -> v1.8.1-rc.1
 * [new tag]         v1.8.1-rc.2   -> v1.8.1-rc.2

c:\z390dev\z390>
c:\z390dev\z390>git rebase upstream/main
Current branch main is up to date.

c:\z390dev\z390>git push origin --follow-tags

until this

a window popped-up on my desktop inviting me to sign-in to github. I thought given past problems, I'd stop there.

Thanks 
John

**Comment by adelosa** [comment] 2023-02-23 00:17
The login is so it can push the tags to your fork on GitHub. Not strictly required. You should try the build now. I will have a look at making the builds work without the tags present.

**Comment by abekornelis** [comment] 2023-02-23 07:58
@adelosa Anthony, if this is a structural problem with any new fork, could we make the command sequence to fix the tags part of the build.bat / build.sh procedures? (without the upload, but at least so new contributors don't have to do it manually)

**Comment by adelosa** [comment] 2023-02-23 20:41
I'll have a look and see what I can do.

**Comment by chookperson** [comment] 2023-02-24 02:33
Guys,
I'd like to thank you both for your patience and endurance.

We're almost there ....

c:\z390dev\z390>build.bat
Could Not Find c:\z390dev\z390\jar\z390.jar
src\az390.java
src\ez390.java
src\gz390.java
src\gz390_screen.java
src\iz390.java
src\lz390.java
src\MessageBox.java
src\mz390.java
src\pz390.java
src\sz390.java
src\test_screen.java
src\test_unicode.java
src\tz390.java
src\vz390.java
src\z390.java
src\zACB.java
src\zc390.java
src\zCatVAIX.java
src\zCatVCLR.java
       19 file(s) copied.
        1 file(s) copied.
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
gz390.java:574: warning: [removal] SecurityManager in java.lang has been deprecated and marked for removal
            SecurityManager sm = System.getSecurityManager();
            ^
gz390.java:574: warning: [removal] getSecurityManager() in System has been deprecated and marked for removal
            SecurityManager sm = System.getSecurityManager();
                                       ^
z390.java:423: warning: [removal] SecurityManager in java.lang has been deprecated and marked for removal
            SecurityManager sm = System.getSecurityManager();
            ^
z390.java:423: warning: [removal] getSecurityManager() in System has been deprecated and marked for removal
            SecurityManager sm = System.getSecurityManager();
                                       ^
4 warnings
z390 version "v1.8.1-7-gb68df64"
'jar.exe' is not recognized as an internal or external command,
operable program or batch file.
bat\bldjar ERROR: Error creating z390.jar file
build.bat ERROR: Encountered RC 9009 - exiting

c:\z390dev\z390>

John

**Comment by adelosa** [comment] 2023-02-25 07:02
This is saying the jar.exe command is not available.. 
If you type `where javac` what directory is it pointing to?
I would expect that jar.exe would be in this folder as part of a standard Java install.
You may need to have a look at your java installation and Windows path to fix this issue.

In terms of addressing the issue of forks not having tags by default - I am starting with a change so that relver will handle error when `git describe` throws an error -- will revert to 'Unversioned' when using Force parameter so that things can progress

I'm still working on best approach for actually getting the tags.. thinking a script at the moment and a reference in the contributing doco..

**Comment by adelosa** [comment] 2023-02-26 00:50
@abekornelis -- I have just created a PR to fix this. I think the solution is simple and works for new contributors. I will need your assistance to do the same change for Windows. As a maintainer of z390 you will have access to my repo to push commits to the PR branch. You will need to setup my fork as a remote to do this - let me know if you need any assistance.. I would ask @jyganci but he also does not use Windows.

**Comment by chookperson** [comment] 2023-02-27 17:44
It appears that I have javac.exe and jar.exe in different directories.
I tried copying jar.exe but got an error on build.bat with a pop-up saying "the procedure entry point could not be found ......".
It would appear that I have two different versions of java installed with javac.exe in C:\Program Files\Common Files\Oracle\Java\javapath\javac.exe and jar.exe in c:\Program Files\java\jdk-17.0.1\bin\jar.exe.

I haven't had a problem with java til now.

Will investigate.

**Comment by chookperson** [comment] 2023-02-27 17:57
Should I re-install JAVA?

**Comment by abekornelis** [comment] 2023-02-27 19:23
The thought has crossed my mind - but as I'm not really a java person I think you're better off following Anthony's advice.

**Closed as completed** 2023-03-06 10:10 UTC
